import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { RadialGradientBG } from "@/components/radial-gradient-bg";
import { BackgroundTwo } from "@/components/background-two";
import { Navbar } from "@/components/navbar";
import { CardGrainy } from "@/components/card-title";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* {/* <body className={inter.className}>{children}</body> */}
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <CardGrainy /> */}
          <main className="flex min-h-screen flex-col items-center pt-6 sm:pt-6 sm:p-16">
            {/* <RadialGradientBG /> */}
            <BackgroundTwo />
            <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm">
              {/* <Navbar /> */}
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
